[01-05 03:47:02] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 03:47:02] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 03_47_02
[01-05 03:47:02] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 03_47_02
[01-05 03:47:02] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 03_47_02
[01-05 03:47:02] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 03_47_02
[01-05 03:47:02] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 03_47_02
[01-05 03:47:13] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 03:47:13] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 03:47:15] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 03:47:16] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 03:47:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:47:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:47:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:47:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:47:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:47:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:47:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:48:33] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 03:48:33] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 03:48:33] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 03:48:33] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 03:48:33] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 03:48:33] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 03:48:33] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 03:48:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 03:49:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:03:12] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:03:12] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_03_12
[01-05 04:03:12] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_03_12
[01-05 04:03:12] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_03_12
[01-05 04:03:12] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_03_12
[01-05 04:03:12] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_03_12
[01-05 04:03:23] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:03:24] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:03:25] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:03:27] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:03:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:03:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:03:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:03:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:03:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:03:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:03:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:04:48] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:04:48] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:04:48] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:04:48] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:04:48] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:04:48] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:04:48] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:04:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:06:00] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:08:10] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:08:10] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_08_10
[01-05 04:08:10] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_08_10
[01-05 04:08:10] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_08_10
[01-05 04:08:10] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_08_10
[01-05 04:08:10] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_08_10
[01-05 04:08:21] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:08:21] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:08:22] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:08:23] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:08:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:08:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:08:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:08:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:08:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:08:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:08:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:09:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:12] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:15:12] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_15_12
[01-05 04:15:12] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_15_12
[01-05 04:15:12] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_15_12
[01-05 04:15:12] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_15_12
[01-05 04:15:12] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_15_12
[01-05 04:15:25] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:15:25] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:15:27] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:15:28] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:35] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:15:37] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:20:59] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:20:59] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_20_59
[01-05 04:20:59] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_20_59
[01-05 04:20:59] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_20_59
[01-05 04:20:59] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_20_59
[01-05 04:20:59] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_20_59
[01-05 04:21:13] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:21:13] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:21:15] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:21:16] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:21:25] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:21:25] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:21:25] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:21:25] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:21:25] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:21:25] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:21:25] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:22:29] [CBIGUtilities.py:442 -         upload_files()] ERROR - [WinError 3] The system cannot find the path specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\multicsv_delete\\63ad7882be79a226c7f0dfa0_CBIG_Delete_TOKEN_3.zip'
[01-05 04:22:29] [CBIGUtilities.py:442 -         upload_files()] ERROR - [WinError 3] The system cannot find the path specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\multicsv_delete\\63ad7882be79a226c7f0dfa0_CBIG_Delete_TOKEN_7.zip'
[01-05 04:22:29] [CBIGUtilities.py:442 -         upload_files()] ERROR - [WinError 3] The system cannot find the path specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\multicsv_delete\\63ad7882be79a226c7f0dfa0_CBIG_Delete_TOKEN_2.zip'
[01-05 04:22:29] [CBIGUtilities.py:442 -         upload_files()] ERROR - [WinError 3] The system cannot find the path specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\multicsv_delete\\63ad7882be79a226c7f0dfa0_CBIG_Delete_TOKEN_6.zip'
[01-05 04:22:29] [CBIGUtilities.py:442 -         upload_files()] ERROR - [WinError 3] The system cannot find the path specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\multicsv_delete\\63ad7882be79a226c7f0dfa0_CBIG_Delete_TOKEN_5.zip'
[01-05 04:22:29] [CBIGUtilities.py:442 -         upload_files()] ERROR - [WinError 3] The system cannot find the path specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\multicsv_delete\\63ad7882be79a226c7f0dfa0_CBIG_Delete_TOKEN_1.zip'
[01-05 04:22:29] [CBIGUtilities.py:442 -         upload_files()] ERROR - [WinError 3] The system cannot find the path specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\multicsv_delete\\63ad7882be79a226c7f0dfa0_CBIG_Delete_TOKEN_4.zip'
[01-05 04:22:36] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:22:36] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_22_36
[01-05 04:22:36] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_22_36
[01-05 04:22:36] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_22_36
[01-05 04:22:36] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_22_36
[01-05 04:22:36] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_22_36
[01-05 04:22:47] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:22:47] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:22:49] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:22:50] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:22:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:22:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:22:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:22:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:22:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:22:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:22:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:23:56] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:23:56] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_23_56
[01-05 04:23:56] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_23_56
[01-05 04:23:56] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_23_56
[01-05 04:23:56] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_23_56
[01-05 04:23:56] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_23_56
[01-05 04:24:08] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:24:08] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:24:10] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:24:11] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:24:18] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:24:18] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:24:18] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:24:18] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:24:18] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:24:18] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:24:18] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:26] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:25:28] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:26:23] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:26:23] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_26_23
[01-05 04:26:23] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_26_23
[01-05 04:26:23] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_26_23
[01-05 04:26:23] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_26_23
[01-05 04:26:23] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_26_23
[01-05 04:26:35] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:26:35] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:26:37] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:26:38] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:26:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:26:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:26:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:26:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:26:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:26:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:26:45] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:53] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:27:55] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:29:16] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 04:29:16] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 04_29_16
[01-05 04:29:16] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 04_29_16
[01-05 04:29:16] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 04_29_16
[01-05 04:29:16] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 04_29_16
[01-05 04:29:16] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 04_29_16
[01-05 04:29:29] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:29:29] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 04:29:31] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 04:29:32] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 04:29:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:29:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:29:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:29:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:29:39] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:30:47] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:30:47] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:31:54] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:31:54] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:31:54] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:31:54] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:31:54] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:31:56] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:31:56] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:31:56] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:31:56] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:31:56] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:32:00] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:32:00] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:32:00] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:32:00] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 04:32:02] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:32:02] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:32:02] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 04:32:02] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 14:50:18] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 14:50:18] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 14_50_18
[01-05 14:50:18] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 14_50_18
[01-05 14:50:18] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 14_50_18
[01-05 14:50:18] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 14_50_18
[01-05 14:50:18] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 14_50_18
[01-05 14:50:37] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 14:50:37] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 14_50_37
[01-05 14:50:37] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 14_50_37
[01-05 14:50:37] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 14_50_37
[01-05 14:50:37] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 14_50_37
[01-05 14:50:37] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 14_50_37
[01-05 14:50:56] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 14:50:57] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 14:50:59] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 14:51:00] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-05 14:51:09] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:11] [CBIGUtilities.py:445 -         upload_files()] ERROR - Expected unicode or bytes, got None
[01-05 14:51:12] [CBIGUtilities.py:445 -         upload_files()] ERROR - Expected unicode or bytes, got None
[01-05 14:51:12] [CBIGUtilities.py:445 -         upload_files()] ERROR - Expected unicode or bytes, got None
[01-05 14:51:12] [CBIGUtilities.py:445 -         upload_files()] ERROR - Expected unicode or bytes, got None
[01-05 14:51:12] [CBIGUtilities.py:445 -         upload_files()] ERROR - Expected unicode or bytes, got None
[01-05 14:51:15] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:16] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:17] [CBIGUtilities.py:445 -         upload_files()] ERROR - Expected unicode or bytes, got None
[01-05 14:51:18] [CBIGUtilities.py:445 -         upload_files()] ERROR - Expected unicode or bytes, got None
[01-05 14:51:22] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:22] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-05 14:51:24] [CBIGUtilities.py:445 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 14:51:24] [CBIGUtilities.py:445 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 14:51:25] [CBIGUtilities.py:445 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 14:51:25] [CBIGUtilities.py:445 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 14:51:25] [CBIGUtilities.py:445 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:01] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 15:18:01] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 15_18_01
[01-05 15:18:01] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 15_18_01
[01-05 15:18:01] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 15_18_01
[01-05 15:18:01] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 15_18_01
[01-05 15:18:01] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 15_18_01
[01-05 15:18:13] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:18:13] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:18:15] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 15:18:17] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 15:18:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:29] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:18:29] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:18:29] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:18:29] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:18:29] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:18:33] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:33] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:36] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:18:36] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:18:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:42] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:42] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:42] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:42] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:42] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:18:49] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:49] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:18:49] [CBIGUtilities.py:450 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:19:33] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 15:19:33] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 15_19_33
[01-05 15:19:33] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 15_19_33
[01-05 15:19:33] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 15_19_33
[01-05 15:19:33] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 15_19_33
[01-05 15:19:33] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 15_19_33
[01-05 15:19:43] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:19:43] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:19:46] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 15:19:47] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 15:19:55] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:19:55] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:19:55] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:19:55] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:19:55] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:19:58] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:19:58] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:19:58] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:19:58] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:19:58] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:20:02] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:20:02] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:20:05] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:20:05] [CBIGUtilities.py:450 -         upload_files()] ERROR - 'username'
[01-05 15:20:34] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 15:20:34] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 15_20_34
[01-05 15:20:34] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 15_20_34
[01-05 15:20:34] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 15_20_34
[01-05 15:20:34] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 15_20_34
[01-05 15:20:34] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 15_20_34
[01-05 15:20:45] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:20:45] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:20:47] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 15:20:49] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 15:20:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:20:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:20:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:20:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:20:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:20:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - 'username'
[01-05 15:20:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - 'username'
[01-05 15:20:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - 'username'
[01-05 15:20:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - 'username'
[01-05 15:20:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - 'username'
[01-05 15:21:04] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:04] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:06] [CBIGUtilities.py:451 -         upload_files()] ERROR - 'username'
[01-05 15:21:06] [CBIGUtilities.py:451 -         upload_files()] ERROR - 'username'
[01-05 15:21:11] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:11] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:11] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:11] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:11] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:13] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:13] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:13] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:13] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:13] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:17] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:17] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:17] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:21:19] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:19] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:19] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:21:44] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 15:21:44] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 15_21_44
[01-05 15:21:44] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 15_21_44
[01-05 15:21:44] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 15_21_44
[01-05 15:21:44] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 15_21_44
[01-05 15:21:44] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 15_21_44
[01-05 15:21:59] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:21:59] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:22:01] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 15:22:03] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 15:23:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:47] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:47] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:47] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:47] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:47] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:50] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:50] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:50] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:50] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:50] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:50] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:50] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:50] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:54] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:54] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:54] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:54] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:54] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:54] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:54] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:54] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:54] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:54] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:57] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:57] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:57] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:23:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:23:57] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:25:53] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 15:25:53] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 15_25_53
[01-05 15:25:53] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 15_25_53
[01-05 15:25:53] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 15_25_53
[01-05 15:25:53] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 15_25_53
[01-05 15:25:53] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 15_25_53
[01-05 15:26:06] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:26:07] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:26:09] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 15:26:14] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 15:26:31] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:31] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:31] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:31] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:31] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:31] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:31] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:31] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:31] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:31] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:34] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:34] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:34] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:34] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:38] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:38] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:38] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:38] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:38] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:38] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:38] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:38] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:38] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:38] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:41] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:41] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:42] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:42] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:42] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:42] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:26:42] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:26:42] [CBIGUtilities.py:453 -         upload_files()] ERROR - 'username'
[01-05 15:27:50] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 15:27:50] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 15_27_50
[01-05 15:27:50] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 15_27_50
[01-05 15:27:50] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 15_27_50
[01-05 15:27:50] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 15_27_50
[01-05 15:27:50] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 15_27_50
[01-05 15:28:06] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:28:06] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 15:28:09] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 15:28:12] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 15:28:29] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:29] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:29] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:29] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:29] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:36] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_5.ZIP': command not understood.
[01-05 15:28:36] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_2.ZIP': command not understood.
[01-05 15:28:36] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_4.ZIP': command not understood.
[01-05 15:28:36] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_1.ZIP': command not understood.
[01-05 15:28:36] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_3.ZIP': command not understood.
[01-05 15:28:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:47] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_6.ZIP': command not understood.
[01-05 15:28:47] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_8.ZIP': command not understood.
[01-05 15:28:47] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_7.ZIP': command not understood.
[01-05 15:28:47] [CBIGUtilities.py:451 -         upload_files()] ERROR - 500 'STORC:\USERS\KHANNAPO\ONEDRIVE - DUN AND BRADSTREET\DOCUMENTS\CBIG\OUTPUTFILES\REPORTTODEWS\MULTICSV_DELETE\63AD7882BE79A226C7F0DFA0_CBIG_DELETE_TOKEN_9.ZIP': command not understood.
[01-05 15:28:51] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:51] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:51] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:51] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:51] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:53] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:53] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:53] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:53] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:53] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:57] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 15:28:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 15:28:59] [CBIGUtilities.py:451 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:28:12] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 22:28:12] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 22_28_12
[01-05 22:28:12] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 22_28_12
[01-05 22:28:12] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 22_28_12
[01-05 22:28:12] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 22_28_12
[01-05 22:28:12] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 22_28_12
[01-05 22:28:21] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:28:21] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:28:23] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 22:28:25] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 22:28:36] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:36] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:36] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:36] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:37] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:43] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:43] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:43] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:43] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:44] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:47] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:48] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:48] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:55] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:55] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:55] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:55] [CBIGUtilities.py:459 -         upload_files()] ERROR - [WinError 2] The system cannot find the file specified: 'filepath'
[01-05 22:28:59] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:59] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:59] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:59] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:28:59] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:29:01] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:01] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:01] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:01] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:01] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:05] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:29:05] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:29:05] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:29:06] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:29:08] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:08] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:08] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:29:08] [CBIGUtilities.py:459 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:31:44] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 22:31:44] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 22_31_44
[01-05 22:31:44] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 22_31_44
[01-05 22:31:44] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 22_31_44
[01-05 22:31:44] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 22_31_44
[01-05 22:31:44] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 22_31_44
[01-05 22:31:52] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:31:52] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:31:54] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 22:31:55] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 22:32:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:10] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:10] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:10] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:10] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:11] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:19] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 22:32:19] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 22_32_19
[01-05 22:32:19] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 22_32_19
[01-05 22:32:19] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 22_32_19
[01-05 22:32:19] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 22_32_19
[01-05 22:32:19] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 22_32_19
[01-05 22:32:29] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:32:29] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:32:31] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 22:32:32] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 22:32:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:40] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:47] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:47] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:47] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:47] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:47] [CBIGUtilities.py:459 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:32:51] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:32:51] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:34:52] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 22:34:52] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 22_34_52
[01-05 22:34:52] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 22_34_52
[01-05 22:34:52] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 22_34_52
[01-05 22:34:52] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 22_34_52
[01-05 22:34:52] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 22_34_52
[01-05 22:35:03] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:35:03] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:35:05] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 22:35:06] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 22:35:13] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:35:13] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:35:13] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:35:13] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:35:13] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:35:20] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:35:20] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:35:20] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:35:20] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:35:20] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:35:20] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:35:20] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:35:20] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:35:20] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:35:20] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:35:25] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:35:25] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:35:46] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 22:35:46] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 22_35_46
[01-05 22:35:46] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 22_35_46
[01-05 22:35:46] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 22_35_46
[01-05 22:35:46] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 22_35_46
[01-05 22:35:46] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 22_35_46
[01-05 22:35:54] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:35:54] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:35:56] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 22:35:56] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 22:36:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:03] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:11] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:36:11] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:36:11] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:36:11] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:36:11] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:36:11] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:36:11] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:36:11] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:36:11] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:36:11] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:36:15] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:15] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:22] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:36:22] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:36:22] [CBIGUtilities.py:453 -         upload_files()] INFO - Connection established 1... 
[01-05 22:36:22] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:36:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:36:26] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:37:52] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-05 22:37:52] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 05_01_2023 22_37_52
[01-05 22:37:52] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 05_01_2023 22_37_52
[01-05 22:37:52] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 05_01_2023 22_37_52
[01-05 22:37:52] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 05_01_2023 22_37_52
[01-05 22:37:52] [CBIGUtilities.py:32 -             __init__()] INFO - Files Deleted from output folder 05_01_2023 22_37_52
[01-05 22:37:59] [CBIGUtilities.py:123 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:37:59] [CBIGUtilities.py:256 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-05 22:38:01] [CBIGUtilities.py:231 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-05 22:38:03] [CBIGUtilities.py:357 - validate_input_files()] INFO - Validation Successfull
[01-05 22:38:10] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:10] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:10] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:10] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:10] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:18] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:38:18] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:38:18] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:38:18] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:38:18] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:38:22] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:22] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:29] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:38:29] [CBIGUtilities.py:461 -         upload_files()] ERROR - SFTPClient.put() missing 1 required positional argument: 'remotepath'
[01-05 22:38:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:34] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:36] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:38:36] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:38:36] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:38:36] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:38:36] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:38:41] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:41] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:41] [CBIGUtilities.py:432 -         upload_files()] INFO - Connection established ... 
[01-05 22:38:43] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:38:43] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-05 22:38:43] [CBIGUtilities.py:461 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
